# match case 

# day = int(input("enter day : "))
# match(day):
#     case 1:
#         print("sun")
#     case 2:
#         print("mon")
#     case 3:
#         print("tue")
#     case 4:
#         print("wed")
#     case 5:
#         print("thurs")
#     case 6:
#         print("fri")
#     case 7:
#         print("sat")
#     case _:
#         print("wrong entry")

#vowel check
# vob = input("enter your alphabet : ")

# match(vob):
#     case "a":
#         print("it is a vobel")
#     case "e":
#         print("it is a vobel")
#     case "i":
#         print("it is a vobel")
#     case "o":
#         print("it is a vobel")
#     case "u":
#         print("it is a vobel")
#     case "_":
#         print("it is a consonent")


# calculator
x = int(input("enter 1st number :"))
y = int(input("enter 2nd number : "))
z = input("enter operand : ")
match(z):
    case"+":
        print(f"sum of {x} and {y} is : ", x + y )
    case"-":
        print("sum of numbers is : ", x - y )
    case"*":
        print("sum of numbers is : ", x * y )
    case"/":
        print("sum of numbers is : ", x / y )
    case "_":
        print("invalid choice")
       